project:
  type: website

website:
  title: "Albury C., MSc"
  navbar:
    title: "Albury C., MSc"
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd
  favicon: "images/favicon-32x32.png"
  page-footer:
    center: "I created this site with [Quarto](https://quarto.org/), an open source scientific publishing system. To see the code that generates this site, [visit the repo here.](https://github.com/alburycatalina/alburycatalina.github.io)"
  cookie-consent: true

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    include-after-body: html/analytics.html
    include-in-header: html/coffee.html

editor: visual

execute:
  freeze: auto

